In [4]:
#numpysiz

a=[1,2,3,4]
b=[5,6,4,7]
ab=[]    fn = np.random.randint(1, 10, size=9).reshape(3, 3)

    print(fn)
    print(np.sum(fn))
    print(fn.sum(axis=1))
    print(fn.sum(axis=0))
    print(fn.min())
    print(fn.max())
    print(fn.argmax())
    print(fn.argmin())

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab

[5, 12, 12, 28]

In [3]:
import numpy as np

In [9]:
a = np.array([5,1,4,8])
b = np.array([2,5,1,12])
a*b

array([10,  5,  4, 96])

In [19]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [22]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [23]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [38]:
#ortalama ilk sıraya standart sapma sonraki ise array boyutu
np.random.normal(10,4,(3,4))

array([[12.07688357,  6.96530023, 16.08805304, 10.72800308],
       [ 4.90679952,  8.28287685, 13.06728405,  4.84720989],
       [16.54706561,  9.29700341,  6.48132608,  3.05697333]])

In [31]:
np.random.randint(0,10,(3,3))

array([[3, 1, 9],
       [8, 2, 7],
       [1, 5, 5]])

In [ ]:
#numpy array özellikleri

In [57]:
array = np.random.randint(10,size = 10)
array

array([7, 6, 6, 3, 0, 4, 0, 4, 6, 0])

In [51]:
array.ndim # boyut

1

In [52]:
array.shape # satır sütun

(10,)

In [53]:
array.size # toplam eleman sayısı

10

In [56]:
matrix = np.random.randint(10,size = (3,5))
matrix

array([[0, 4, 2, 2, 4],
       [6, 3, 5, 8, 4],
       [4, 5, 7, 6, 2]])

In [58]:
matrix.ndim

2

In [59]:
matrix.shape

(3, 5)

In [60]:
matrix.size

15

In [68]:
#Yeniden Şekillendirme(Reshape)

In [72]:
array1 = np.arange(1,10)

In [73]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
#reshape fonksiyonu değeri kadarını dönüştürür mesela 9 değer varsa 3*3 1*9 9*1 yapa bilir fakat resize bir arrayde az değer olsada boş kalan yerlere aynı değerleri atar

In [86]:
np.resize(a,(3,3))#aynı işlem bunda çalıştı

array([[5, 1, 4],
       [8, 5, 1],
       [4, 8, 5]])

In [88]:
np.reshape(a,(3,3))#aynı işlem bunda çalışmadı

ValueError: cannot reshape array of size 4 into shape (3,3)

In [91]:
np.reshape(array1,(1,9))#iki boyuta çevrildi

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [92]:
#Birleştirme (Concatenation)

In [93]:
array2 = np.array([5,4,9]) 
array3 = np.array([9,5,1]) 

In [94]:
np.concatenate([array2,array3])

array([5, 4, 9, 9, 5, 1])

In [95]:
#2 boyut için

In [96]:
array2 = np.array([[5,4,9],
                   [6,4,8]]) 
array3 = np.array([[9,5,1],
                   [4,5,7]]) 

In [98]:
np.concatenate([array2,array3],axis = 0) #0 satırsal birleştirme

array([[5, 4, 9],
       [6, 4, 8],
       [9, 5, 1],
       [4, 5, 7]])

In [99]:
np.concatenate([array2,array3],axis = 1) #1 sütunsal birleştirme

array([[5, 4, 9, 9, 5, 1],
       [6, 4, 8, 4, 5, 7]])

In [100]:
#Array Ayırma (Splitting)

In [102]:
x = np.array([1,2,3,99,99,3,2,1])

In [104]:
a,b,c = np.split(x,[3,5])

In [7]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
ust,alt=np.vsplit(m, [2])

In [27]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
sol,sag=np.hsplit(m,[2])

In [25]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [29]:
np.sort(sol)#array yapısını direk değiştirir

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [31]:
np.random.randint(10,size=(3,3,2))

array([[[1, 7],
        [5, 0],
        [6, 0]],

       [[4, 4],
        [4, 7],
        [8, 1]],

       [[3, 6],
        [4, 2],
        [3, 2]]])

In [1]:
#pycharm not al

In [ ]:
#Index ile Elemanlara Erişmek

In [3]:
a = np.random.randint(10,size = 15)

a

array([7, 4, 8, 1, 9, 6, 4, 9, 4, 9])

In [4]:
a[0]

7

In [7]:
b = np.random.randint(10,size = (3,5))
b

array([[4, 0, 3, 5, 1],
       [3, 4, 8, 2, 4],
       [7, 1, 0, 8, 5]])

In [9]:
b[0,0]

4

In [10]:
b[1,3]

2

In [15]:
b[1,4] = 5.5#ondalıklı kısmı kesti
b[1,4]

5

In [16]:
b

array([[4, 0, 3, 5, 1],
       [3, 4, 8, 2, 5],
       [7, 1, 0, 8, 5]])

In [17]:
#Array Alt Küme İşlemleri

In [18]:
t = np.arange(20,30)
t

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
t[0:3]

array([20, 21, 22])

In [21]:
p = np.random.randint(10,size = (5,5))
p

array([[2, 0, 8, 1, 2],
       [0, 7, 0, 8, 3],
       [5, 4, 4, 6, 4],
       [1, 2, 7, 0, 7],
       [3, 5, 4, 3, 1]])

In [25]:
p[1:3,1:3]#virgul öncesi satırlar sonrası sütunlar

array([[7, 0],
       [4, 4]])

In [29]:
p[:,0]

array([2, 0, 5, 1, 3])

In [28]:
p[0,:]

array([2, 0, 8, 1, 2])

In [36]:
p[0,1:3]

array([0, 8])

In [63]:
#Array Alt Küme İşlemleri

In [69]:
a = np.random.randint(10,size = (5,5))

In [70]:
a

array([[6, 5, 6, 0, 6],
       [2, 4, 2, 6, 4],
       [9, 8, 9, 5, 1],
       [7, 9, 3, 5, 3],
       [6, 8, 4, 3, 4]])

In [71]:
alt1 = a[0:3,0:2]
alt1

array([[6, 5],
       [2, 4],
       [9, 8]])

In [72]:
alt1[0,0] = 999
alt1[1,1] = 9999

In [73]:
alt1

array([[ 999,    5],
       [   2, 9999],
       [   9,    8]])

In [76]:
#alt kümede yaptığımız değişkenlikler genel kümeyede değişiklik yapar
a

array([[ 999,    5,    6,    0,    6],
       [   2, 9999,    2,    6,    4],
       [   9,    8,    9,    5,    1],
       [   7,    9,    3,    5,    3],
       [   6,    8,    4,    3,    4]])

In [84]:
#ana array bozulmaması için copy fonksiyonu kullanılır
alt2 = a[0:3,0:2].copy()
alt2

array([[ 999,    5],
       [   2, 9999],
       [   9,    8]])

In [85]:
alt2[0,0] = 1
alt2[0,1] = 2

In [86]:
a

array([[ 999,    5,    6,    0,    6],
       [   2, 9999,    2,    6,    4],
       [   9,    8,    9,    5,    1],
       [   7,    9,    3,    5,    3],
       [   6,    8,    4,    3,    4]])

In [87]:
alt2

array([[   1,    2],
       [   2, 9999],
       [   9,    8]])

In [90]:
#Fancy Index ile Elemanlara Erişmek (ilerleyen bölümlerde en önemli kavramlardan pandas ve numpy arraylerinde kullanılacak)

In [92]:
v = np.arange(0,30,3)

In [94]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [99]:
#farklı farklı yerdeki birden fazla verilere erişmek için bunları tek seferde yapmak için fancy index

In [100]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [101]:
al=[1,3,5]
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [102]:
v[al]#fancy index

array([ 3,  9, 15])

In [103]:
t=np.arange(9).reshape(3,3)

In [110]:
t

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [125]:
satir = np.array([1,2])
sütun = np.array([2,1])

In [129]:
t[satir,sütun]

array([5, 7])

In [133]:
#hem fancy hem nırmal
t[1,[0,2]]

array([3, 5])

In [135]:
#slice ile fancy
t[1:,[0,2]]

array([[3, 5],
       [6, 8]])

In [1]:
#array boolean

In [4]:
t = np.arange(10)

In [5]:
t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
t < 5#teker teker bütün hepsini sorgular

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [8]:
t[t < 5]#fancy index ile bu sorgunun verdiği indexteki elemanları alırız

array([0, 1, 2, 3, 4])

In [10]:
#örnek bütün mantıksal işlemler kullanılır
f = np.arange(10)
print(f)
print(f[(f % 2 == 0)])
p = f[(f % 2 == 0)]
p[0] = 100
print(p)
print(f)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[100   2   4   6   8]
[0 1 2 3 4 5 6 7 8 9]


In [11]:
t[(t % 2 == 0)]

array([0, 2, 4, 6, 8])

In [13]:
s1 = np.random.randint(10, size=10)
s2 = np.random.randint(10, size=10)
print(s1)
print(s2)

[4 1 1 8 4 1 2 3 0 6]
[0 5 1 2 1 2 7 4 8 3]


In [14]:
print(s1 > s2)
print(s1 < s2)

[ True False False  True  True False False False False  True]
[False  True False False False  True  True  True  True False]


In [16]:
print(np.all(s1 > s2))#s1deki heğsi s2den büyükmü
print(np.any(s1 > s2))#s1deki s2deki herhangi birinden büyükmü

False
True


In [25]:
math = np.linspace(0,19,11)
math

array([ 0. ,  1.9,  3.8,  5.7,  7.6,  9.5, 11.4, 13.3, 15.2, 17.1, 19. ])

In [30]:
math+2

array([ 2. ,  3.9,  5.8,  7.7,  9.6, 11.5, 13.4, 15.3, 17.2, 19.1, 21. ])

In [26]:
math-1

array([-1. ,  0.9,  2.8,  4.7,  6.6,  8.5, 10.4, 12.3, 14.2, 16.1, 18. ])

In [27]:
math**2

array([  0.  ,   3.61,  14.44,  32.49,  57.76,  90.25, 129.96, 176.89,
       231.04, 292.41, 361.  ])

In [28]:
math*2

array([ 0. ,  3.8,  7.6, 11.4, 15.2, 19. , 22.8, 26.6, 30.4, 34.2, 38. ])

In [57]:
at = math/2
at

array([0.  , 0.95, 1.9 , 2.85, 3.8 , 4.75, 5.7 , 6.65, 7.6 , 8.55, 9.5 ])

In [31]:
first = np.random.randint(1, 10, size=5)
second = np.random.randint(2, 12, size=5)
first

array([1, 8, 1, 9, 1])

In [32]:
second

array([ 4,  8, 11,  3,  4])

In [33]:
np.add(first,second)

array([ 5, 16, 12, 12,  5])

In [50]:
eksi = np.subtract(first,second)
eksi

array([ -3,   0, -10,   6,  -3])

In [39]:
t1 = np.multiply(first,second)

In [40]:
t2 = np.divide(first,second)

In [37]:
np.power(first,second)

array([       1, 16777216,        1,      729,        1], dtype=int32)

In [38]:
np.power(first,2)#kuvvet

array([ 1, 64,  1, 81,  1], dtype=int32)

In [43]:
np.sqrt(first)#kök

array([1.        , 2.82842712, 1.        , 3.        , 1.        ])

In [44]:
np.exp(first)#verilen arrayin üstelini hesaplar

array([2.71828183e+00, 2.98095799e+03, 2.71828183e+00, 8.10308393e+03,
       2.71828183e+00])

In [46]:
np.mod(first,2)

array([1, 0, 1, 1, 1], dtype=int32)

In [41]:
np.array_equal(t1, t2)#iki dizi aynı öğelere ve şekle sahipse true çıkar

False

In [56]:
np.abs(eksi)# mutlak değer

array([ 3,  0, 10,  6,  3])

In [58]:
np.ceil(at)# en yakın tam sayıya yuvarlar

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [59]:
np.floor(at)# en yakın tam sayının altına yuvarlar

array([0., 0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [60]:
np.round(at)# en yakın integer değerine yuvarlar

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [52]:
#np sin cos gibi trigonometrik ifadeler , logaretmik ifadeler işlem yapar

In [55]:
fn = np.random.randint(1, 10, size=9).reshape(3, 3)

print(fn)
print(np.sum(fn))#iki boyutlu fonksiyondaki bütün değerleri toplar
print(fn.sum(axis=1))#satırları toplar ve array yapar
print(fn.sum(axis=0))#sütunları toplar ve array yapar
print(fn.min())#min değer bulur
print(fn.max())#max değer bulur 
print(fn.argmax())
print(fn.argmin())

[[7 6 9]
 [8 3 4]
 [7 3 6]]
53
[22 15 16]
[22 12 19]
3
9
2
4


In [61]:
#istatistiksel işlemler

In [64]:
ist = np.random.randint(1,10,(3,5))
ist

array([[3, 7, 2, 4, 7],
       [5, 3, 3, 4, 8],
       [6, 1, 7, 4, 8]])

In [65]:
np.mean(ist,axis=0)#verilen arrayde her sütunun ortalaması axis değeri 1 olsaydı satır olucaktı

array([4.66666667, 3.66666667, 4.        , 4.        , 7.66666667])

In [66]:
np.mean(ist)#genel ortalama

4.8

In [67]:
np.var(ist,axis=0)#verilen arrayde her sütunun varyansını döndürür

array([1.55555556, 6.22222222, 4.66666667, 0.        , 0.22222222])

In [68]:
np.std(ist)#standart sapmasını verir axis ile satır sütun belirlenebilir

2.1664102412362563

In [70]:
np.median(ist,axis=0)#medyanı verir

array([5., 3., 3., 4., 8.])