In [16]:
import numpy as np 
import pandas as pd
import seaborn as sns

In [2]:
V1 = pd.array([1,3,6,5,7])
V2 = pd.array([7,7,5,8,12])
V3 = pd.array([6,12,5,6,14])

df = pd.DataFrame({"V1":V1,
                   "V2":V2,
                   "V3":V3})
df = df.astype(float)
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [3]:
from sklearn import preprocessing

In [4]:
preprocessing.scale(df)# ortalaması 0 standart sapması 1 işlemi

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [5]:
#Normalizasyon

In [6]:
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

In [7]:
#Min Max Dönüşümü

In [8]:
scaler = preprocessing.MinMaxScaler(feature_range = (10,20))
scaler.fit_transform(df)#Varyans yapısı korundu ölçekleri değişti(öncekilerde dahil)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])

In [9]:
#Binarize Dönüşüm

In [10]:
#Standartlaştırma değiş Dönüştürmedir

In [11]:
binarizer = preprocessing.Binarizer(threshold = 5).fit(df)

In [14]:
binarizer.transform(df)#eşik değeri 5 verdiğimiz için altı ve üstü değerler için binary değer verir

array([[0., 1., 1.],
       [0., 1., 1.],
       [1., 0., 0.],
       [0., 1., 1.],
       [1., 1., 1.]])

In [15]:
#0-1 Dönüşümü

In [17]:
tips = sns.load_dataset("tips")
df = tips.copy()
df_l = df.copy()

In [18]:
df_l.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [19]:
df_l["yeni_sex"] = df["sex"].cat.codes

In [20]:
df_l.head()#cat ile ilk değer 1 olur preprocessing ile 0 olur

total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         1
1       10.34  1.66    Male     No  Sun  Dinner     3         0
2       21.01  3.50    Male     No  Sun  Dinner     3         0
3       23.68  3.31    Male     No  Sun  Dinner     2         0
4       24.59  3.61  Female     No  Sun  Dinner     4         1

In [21]:
# 1 ve diğerleri(0)

In [23]:
df_l["yeni_day"] = np.where(df_l["day"].str.contains("Sun"),1,0)

In [25]:
df_l.head(20)

total_bill   tip     sex smoker  day    time  size  yeni_sex  yeni_day
0        16.99  1.01  Female     No  Sun  Dinner     2         1         1
1        10.34  1.66    Male     No  Sun  Dinner     3         0         1
2        21.01  3.50    Male     No  Sun  Dinner     3         0         1
3        23.68  3.31    Male     No  Sun  Dinner     2         0         1
4        24.59  3.61  Female     No  Sun  Dinner     4         1         1
5        25.29  4.71    Male     No  Sun  Dinner     4         0         1
6         8.77  2.00    Male     No  Sun  Dinner     2         0         1
7        26.88  3.12    Male     No  Sun  Dinner     4         0         1
8        15.04  1.96    Male     No  Sun  Dinner     2         0         1
9        14.78  3.23    Male     No  Sun  Dinner     2         0         1
10       10.27  1.71    Male     No  Sun  Dinner     2         0         1
11       35.26  5.00  Female     No  Sun  Dinner     4         1         1
12       15.42  1.57    Male     No  Sun  Dinner     2         0         1
13       18.43  3.00    Male     No  Sun  Dinner     4         0         1
14       14.83  3.02  Female     No  Sun  Dinner     2         1         1
15       21.58  3.92    Male     No  Sun  Dinner     2         0         1
16       10.33  1.67  Female     No  Sun  Dinner     3         1         1
17       16.29  3.71    Male     No  Sun  Dinner     3         0         1
18       16.97  3.50  Female     No  Sun  Dinner     3         1         1
19       20.65  3.35    Male     No  Sat  Dinner     3         0         0

In [26]:
#Çok Sınıflı Dönüşüm

In [27]:
lbe = preprocessing.LabelEncoder()

In [28]:
df_l["daha_yeni_gun"] = lbe.fit_transform(df_l["day"])

In [29]:
df_l

total_bill   tip     sex smoker   day    time  size  yeni_sex  yeni_day  \
0         16.99  1.01  Female     No   Sun  Dinner     2         1         1   
1         10.34  1.66    Male     No   Sun  Dinner     3         0         1   
2         21.01  3.50    Male     No   Sun  Dinner     3         0         1   
3         23.68  3.31    Male     No   Sun  Dinner     2         0         1   
4         24.59  3.61  Female     No   Sun  Dinner     4         1         1   
..          ...   ...     ...    ...   ...     ...   ...       ...       ...   
239       29.03  5.92    Male     No   Sat  Dinner     3         0         0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1         0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0         0   
242       17.82  1.75    Male     No   Sat  Dinner     2         0         0   
243       18.78  3.00  Female     No  Thur  Dinner     2         1         0   

     daha_yeni_gun  
0                2  
1                2  
2                2  
3                2  
4                2  
..             ...  
239              1  
240              1  
241              1  
242              1  
243              3  

[244 rows x 10 columns]

In [30]:
#Bu dönüşümde algoritmaların kafası karışır kategorik değişkenlerin bağımlı değişkenlere etkileri bozulmaktadır
#aralarında fark olamayan nominal depişkenlerde bu değerler fark yaratacak ve
#bu dönüşüm zararlı olacaktır

In [31]:
#One-Hot Dönüşümleri

In [32]:
df_one_hot = df.copy()

In [33]:
pd.get_dummies(df_one_hot, columns = ["sex"], prefix = ["sex"]).head()

total_bill   tip smoker  day    time  size  sex_Male  sex_Female
0       16.99  1.01     No  Sun  Dinner     2         0           1
1       10.34  1.66     No  Sun  Dinner     3         1           0
2       21.01  3.50     No  Sun  Dinner     3         1           0
3       23.68  3.31     No  Sun  Dinner     2         1           0
4       24.59  3.61     No  Sun  Dinner     4         0           1

In [34]:
#aynı bilgiyi taşıyon 3 değişken olucaktı. Birbirleri üzeirrnden oluşturulabiliyorsa dummy değişken tuzağı denir
#bundan dolayı ilk orjinal veri çıkmalı ve bu aynı şeyi ifade edenlerden biirde çıkmaldır

In [35]:
#Sürekli Değişkeni Kategorik Değişkene Çevirme

In [37]:
dff = df.select_dtypes(include = ["float64","int64"])

In [40]:
est = preprocessing.KBinsDiscretizer(n_bins=[3,2,2], encode = "ordinal", strategy = "quantile").fit(dff)

In [41]:
est.transform(dff)[0:10]

array([[1., 0., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.]])

In [42]:
#genelde bu işlemi yapmak ölçeğini bozmak pozitif bişey değildir algoritmalar zaten yapmaktadır

In [43]:
#Değişkeni İndexe, İndexi Değişkene Çevirmek

In [44]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [45]:
df["yeni_degisken"] = df.index

In [47]:
#var olan değişkeni index olarak eklemek istersek

In [48]:
df["yeni_degisken"] = df["yeni_degisken"] + 10

In [50]:
df.index = df["yeni_degisken"]

In [51]:
df

total_bill   tip     sex smoker   day    time  size  \
yeni_degisken                                                        
10                  16.99  1.01  Female     No   Sun  Dinner     2   
11                  10.34  1.66    Male     No   Sun  Dinner     3   
12                  21.01  3.50    Male     No   Sun  Dinner     3   
13                  23.68  3.31    Male     No   Sun  Dinner     2   
14                  24.59  3.61  Female     No   Sun  Dinner     4   
...                   ...   ...     ...    ...   ...     ...   ...   
249                 29.03  5.92    Male     No   Sat  Dinner     3   
250                 27.18  2.00  Female    Yes   Sat  Dinner     2   
251                 22.67  2.00    Male    Yes   Sat  Dinner     2   
252                 17.82  1.75    Male     No   Sat  Dinner     2   
253                 18.78  3.00  Female     No  Thur  Dinner     2   

               yeni_degisken  
yeni_degisken                 
10                        10  
11                        11  
12                        12  
13                        13  
14                        14  
...                      ...  
249                      249  
250                      250  
251                      251  
252                      252  
253                      253  

[244 rows x 8 columns]