# 1 - Introduction & Images

In [3]:
import cv2

#Loading an Image
img = cv2.imread('assets/besiktas.png')
gray_img = cv2.imread('assets/besiktas.png', 0)
print(img.shape)
print(gray_img.shape)

(768, 512, 3)
(768, 512)


In [4]:
#Displaying an Image
cv2.imshow("Image", img)
cv2.imshow("Gray Image", gray_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
#Resizing and Rotating an Image

In [15]:
img = cv2.resize(img, (150, 200))
img_re = cv2.resize(img, (0, 0), fx = 0.5, fy = 0.5)#resmi yarı yarıya indirir 2 ve 2 yaparsak 2 katına çıkar
img_ro = cv2.rotate(img, cv2.cv2.ROTATE_180)

cv2.imshow("Image", img)
cv2.imshow("Resize Image", img_re)
cv2.imshow("Rotate Image", img_ro)
cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.imwrite('new_img.jpg', img_ro)

True

# 2 - Image Fundamentals and Manipulation

In [47]:
import cv2
import random
img = cv2.imread('assets/besiktas.png')

In [19]:
#Image Representation
print(img)#görünüşü
print(type(img))#tipi
print(img.shape)#boyutu

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
<class 'numpy.ndarray'>
(768, 512, 3)


In [29]:
#Accessing Pixel Values
print(img[500][256])#0 satır 0 sütundaki rgb değerleri BGR

[  5   5 224]


In [37]:
#Changing Pixel Colors
for i in range(img.shape[0]):
    for j in range(100):
        img[i][j] = [random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)]
        
cv2.imshow("Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [48]:
#Copying & Pasting Parts of Image
flag = img[384:576, 171:341]

img[100:292, 100:270] = flag
cv2.imshow("Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 3 - Cameras and VideoCapture

In [4]:
import cv2
import numpy as np

In [5]:
#Displaying video capture device
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()#ret cihaz kullanılıyorsa hata döndürür frame ise her saniyedeki numpy görüntüsü
    
    cv2.imshow('frame', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

In [13]:
#Mirroring video multiple times
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()#ret cihaz kullanılıyorsa hata döndürür frame ise her saniyedeki numpy görüntüsü
    width = int(cap.get(3))
    height = int(cap.get(4))    
    
    img = np.zeros(frame.shape, np.uint8)
    smaller_frame = cv2.resize(frame, (0,0), fx = 0.5, fy = 0.5)
    
    img[:height//2, :width//2] = smaller_frame
    img[:height//2, width//2:] = cv2.flip(smaller_frame, 1)
    img[height//2:, :width//2] = cv2.flip(smaller_frame, 0)
    img[height//2:, width//2:] = cv2.flip(cv2.flip(smaller_frame, 0), 1)
    
    cv2.imshow('frame', img)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

# 4 - Drawing (Lines, Images, Circles & Text)


In [2]:
import cv2
import numpy as np

In [38]:
#Drawing Lines
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()#ret cihaz kullanılıyorsa hata döndürür frame ise her saniyedeki numpy görüntüsü
    width = int(cap.get(3))
    height = int(cap.get(4))    
    
    #Drawing Lines
    img = cv2.line(frame, (0,0), (width, height), (0, 0, 255), 10)#(x,y) x sağa y sola ilk tuple ilk köşe ikinci tuple ikinci köşe, renk, kalınlık
    img = cv2.line(frame, (0,height), (width, 0), (0, 0, 255), 10)
    
    #Drawing Rectangles
    img = cv2.rectangle(frame, (0,0), (width, height), (0, 0, 255), 10)
    img = cv2.circle(frame, (width//2, height//2), 60, (255, 0, 255), -1)#-1 ise içi dolu olur
    
    #Drawing Text
    font = cv2.FONT_HERSHEY_SIMPLEX
    img = cv2.putText(img, 'Tolga', (10, height-20), font, 1, (0,0,0), 5, cv2.LINE_AA)# text , centerposition, font, fontscale, color, linethickness, line type
    
    cv2.imshow('frame', img)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

# 5 - Colors and Color Detection

In [36]:
import cv2
import numpy as np

In [45]:
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()#ret cihaz kullanılıyorsa hata döndürür frame ise her saniyedeki numpy görüntüsü
    width = int(cap.get(3))
    height = int(cap.get(4))    
    
    #HSV Color
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    lower_blue = np.array([90, 50, 50])
    upper_blue = np.array([130, 255, 255])
    
    #Masks
    mask = cv2.inRange(hsv, lower_blue, upper_blue)
    
    result = cv2.bitwise_and(frame, frame, mask = mask)
    
    cv2.imshow('result', result)#verilen hsv değerleri arasındakine görüntüyü gösterir
    cv2.imshow('frame', mask)#verilen hsv değerleri arasındakine görüntüyü 2li olarak gösterir
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

# 6 - Corner Detection

In [36]:
import cv2
import numpy as np

In [72]:
#Corner detection
img = cv2.imread('assets/chessboard.png')
img = cv2.resize(img, (0, 0), fx = 0.5, fy = 0.5)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

corners = cv2.goodFeaturesToTrack(gray, 100, 0.01, 10)#köşe sayısı ?, minumum quality, köşeler arasındaki min mesafe 
corners = np.int0(corners)

#Drawing corners  
for corner in corners:
    x, y = corner.ravel()#[[[1,2,3]]] içindekileri alır
    img = cv2.circle(img, (x,y), 5, (0, 255, 255), -1)
    #img = cv2.rectangle(img, tuple(corner[0]), tuple(corner[0]), (255, 255, 255), 10) benimki


#Drawing lines between corners
for i in range(len(corners)):
    for j in range(i+1, len(corners)):#sonraki köşe için
        corner1 = tuple(corners[i][0])
        corner2 = tuple(corners[j][0])
        color = tuple(map(lambda x: int(x), np.random.randint(0, 255, size = 3)))
        img = cv2.line(img, corner1, corner2, color, 1)
    
cv2.imshow("Chess Board", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 7 - Template Matching (Object Detection)

In [1]:
import cv2 
import numpy as np

In [21]:
img = cv2.imread('assets/soccer_practice.jpg', 0)#gray scale
img = cv2.resize(img, (0,0), fx = 0.75, fy = 0.75)
template = cv2.imread('assets/shoe.png', 0)
template = cv2.resize(template, (0,0), fx = 0.75, fy = 0.75)
h, w = template.shape

#Template Matching
methods = [cv2.TM_CCOEFF, cv2.TM_CCOEFF_NORMED, cv2.TM_CCORR, cv2.TM_CCORR_NORMED, cv2.TM_SQDIFF, cv2.TM_SQDIFF_NORMED]

for method in methods:
    img2 = img.copy()
    
    #Theory Behind Template Matching
    result = cv2.matchTemplate(img2, template, method)
    min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)
    if method in [cv2.TM_SQDIFF, cv2.TM_SQDIFF_NORMED]:
        location = min_loc
    else:
        location = max_loc
    
    #Displaying Matches
    bottom_right = (location[0] + w, location[1] + h)
    cv2.rectangle(img2, location, bottom_right, 255, 5)

    cv2.imshow("Match", img2)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

# 8 - Face and Eye Detection

In [3]:
import cv2
import numpy as np

In [18]:
cap = cv2.VideoCapture(0)
face_cascade = cv2.CascadeClassifier('haarcascade-frontalface-default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade-eye.xml')


while True:
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for x,y,w,h in faces:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (255,255,255), 5)
        roi_gray = gray[y:y+h, x:x+w]
        roi_frame = frame[y:y+h, x:x+w]
        
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.3, 5)
        for ex,ey,ew,eh in eyes:
            cv2.rectangle(roi_frame, (ex,ey), (ex+ew, ey+eh), (0,0,0), 5)
            
        
    cv2.imshow("Video", frame)
    if cv2.waitKey(1) == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()