In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import roc_auc_score,roc_curve
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from warnings import filterwarnings
filterwarnings('ignore')

In [5]:
diabetes = pd.read_csv('diabetes.csv')
df = diabetes.copy()
df = df.dropna()
y = df['Outcome']
X = df.drop(['Outcome'],axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.30, random_state = 44)

In [7]:
nb = GaussianNB()
nb_model = nb.fit(X_train, y_train)
nb_model

GaussianNB()

In [8]:
#TAHMİN

In [10]:
nb_model.predict(X_test)[0:5]

array([0, 1, 1, 0, 1], dtype=int64)

In [12]:
nb_model.predict_proba(X_test)[0:5]

array([[9.08556958e-01, 9.14430423e-02],
       [3.24799980e-05, 9.99967520e-01],
       [3.80132717e-01, 6.19867283e-01],
       [9.50423390e-01, 4.95766095e-02],
       [2.05274751e-01, 7.94725249e-01]])

In [15]:
y_pred = nb_model.predict(X_test)

In [17]:
confusion_matrix(y_test, y_pred)

array([[132,   9],
       [ 36,  54]], dtype=int64)

In [18]:
accuracy_score(y_test, y_pred)

0.8051948051948052

In [19]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.94      0.85       141
           1       0.86      0.60      0.71        90

    accuracy                           0.81       231
   macro avg       0.82      0.77      0.78       231
weighted avg       0.81      0.81      0.80       231



In [21]:
cross_val_score(nb_model, X_test, y_test, cv = 10).mean()

0.7922101449275363